Fixup build on Qt6
sailfishos/nemo-qml-plugin-connectivity pull request #8
Opened 2024-03-12 07:06 UTC by neochapay

2024-03-12 08:31 UTC, pvuorela commented on src/nemo-connectivity/settingsvpnmodel.cpp
> +#if (QT_VERSION < QT_VERSION_CHECK(6, 0, 0))
Should be 5.14

2024-03-12 08:31 UTC, pvuorela commented on src/nemo-connectivity/settingsvpnmodel.cpp
> +#if (QT_VERSION < QT_VERSION_CHECK(6, 0, 0))
5.14 or suppose std::endl should work too.

2024-03-12 08:31 UTC, pvuorela commented on src/nemo-connectivity/settingsvpnmodel.cpp
> +        if(provisioningFile.open(QIODevice::ReadOnly)) {
if () as per convention. Repeating many times below too, including while() case.

2024-03-12 08:31 UTC, pvuorela commented on src/nemo-connectivity/settingsvpnmodel.cpp
> +            provisioningFile.close();
Closing not happening on old code paths?

2024-03-12 08:31 UTC, pvuorela commented on src/nemo-connectivity/settingsvpnmodel.cpp
> +#else
If the code block below does the same thing (that I didn't try to follow yet), it should be compatible with older Qt versions and could be used instead of #ifdeffing?

2024-03-12 08:31 UTC, pvuorela commented on src/nemo-connectivity/nemo-connectivity.pro
> +    QT+=xml
Stylistic nitpicking: keep spaces around the assignment operator.

2024-03-12 13:09 UTC, neochapay commented on src/nemo-connectivity/settingsvpnmodel.cpp
> +#else
Not checked with old code

2024-03-12 16:07 UTC, pvuorela requested changes
You just resolved the comments without really providing rationale for questions or doing requested changed. I'll mark this needing changes.

2024-03-12 16:41 UTC, neochapay commented
@pvuorela pushed new code

2024-03-14 08:47 UTC, pvuorela commented
Maybe I wasn't clear enough:
- The if() and while() type of code should be "if ()" and "while ()" as per coding conventions. We've been through this multiple times already on different places.
- If we need to eventually migrate away from QtXmlPatterns and it's as easy as that, why wouldn't we do that already with Qt 5.6, i.e. remove the xml patterns usage altogether here. I don't see anything 5.14 specific on that either.             
- This does provisioningFile.close() which wasn't there earlier, isn't done on other file processing methods, and on a file that gets closed anyway. Again: why is this there and why should it be responsibility of the method?

2024-03-14 11:48 UTC, neochapay commented
@pvuorela can you get me xml config file for test or add test for correct migration from QtXmlPatterns

2024-03-14 12:33 UTC, pvuorela commented
@LaakkonenJussi maybe you'd have some test file for this. ^

2024-03-14 15:28 UTC, LaakkonenJussi commented
> @LaakkonenJussi maybe you'd have some test file for this. ^

Something like this https://docs.fortinet.com/document/forticlient/6.2.0/xml-reference-guide/858086/ssl-vpn could be added as a unit test. But maybe that deserves a task of its own, will try tomorrow/next week with something whipped with that info to test this PR.

2024-03-20 12:29 UTC, LaakkonenJussi commented
> > @LaakkonenJussi maybe you'd have some test file for this. ^
> 
> Something like this https://docs.fortinet.com/document/forticlient/6.2.0/xml-reference-guide/858086/ssl-vpn could be added as a unit test. But maybe that deserves a task of its own, will try tomorrow/next week with something whipped with that info to test this PR.

That file on fortinet.com actually seemed to be broken. I'll add some files you could test that they still work with the newer Qt build (as only these seemed to be affected):
[fortinet_openconnect_examples.tar.gz](https://github.com/sailfishos/nemo-qml-plugin-connectivity/files/14666343/fortinet_openconnect_examples.tar.gz)
  - .xml's are for OpenConnect
  - .conf is for FortiVPN

2026-03-23 08:49 UTC, pvuorela reviewed
The commits are now in some strange state where majority of the changes are in a duplicated commit of my earlier PR merge commit. And the other commit changing one line is saying it's fixing build on "qt6 < 6.5". Really?

2026-03-23 08:49 UTC, pvuorela commented on src/nemo-connectivity/settingsvpnmodel.cpp
> +#include <QSettings>
Not following why these are moved out of the group of other basic qt includes.

2026-03-23 08:49 UTC, pvuorela commented on src/nemo-connectivity/settingsvpnmodel.cpp
> +        if(!provisioningFile.open(QIODevice::ReadOnly)) {
Do remember the qt conventions on all of these.

2026-03-23 11:14 UTC, pvuorela commented
Still having the bad merge commit.

2026-03-23 12:10 UTC, neochapay commented
> Still having the bad merge commit.

fixed

2026-04-14 14:48 UTC, PureTryOut commented
What's the current state of this?

2026-04-15 06:48 UTC, pvuorela reviewed
Current status as it has been long time: there's something but it doesn't really work.

Otherwise I'd just close this by now but there are some nice protocol examples attached. Actually those might be good to include in the repository to allow later check what's supposed to be parsed.

For something mergeable I'd like both Qt5 and Qt6 using the same code. The API used here for qt6 should per se work fine with older versions.

@PureTryOut If you wanna pick this up, at this point I'd consider competing PRs welcome too.

2026-04-15 06:48 UTC, pvuorela commented on src/nemo-connectivity/settingsvpnmodel.cpp
> +                if (element.tagName() == "Name") {
All of this is not really doing the same thing as the earlier code. This shouldn't just go through the elements hoping to find specific element names, but rather dive into /AnyConnectProfile/ServerList/HostEntry and parse the content there. Anything outside that should be ignored.

Then again this doesn't look like it's diving too deep anyway since it's just nextSibling(), not getting child elements.

Then again even if this would dive deeper, looks like it's not checking the correct element names. Above is "HostName" while this looks for name etc. I don't any of these would work.

2026-04-15 06:48 UTC, pvuorela commented on src/nemo-connectivity/settingsvpnmodel.cpp
> +            QDomElement element = configNode.toElement();
Likewise with the other format, this is hardly parsing it properly.

2026-04-15 08:08 UTC, PureTryOut commented on src/nemo-connectivity/settingsvpnmodel.cpp
> +                if (element.tagName() == "Name") {
So I know nothing about FortiVPN but KDE also supports it and seems to parse the config in https://invent.kde.org/plasma/plasma-nm/-/blob/master/vpn/fortisslvpn/fortisslvpnwidget.cpp?ref_type=heads#L78. We could probably reuse logic from there? Sadly it's not in a usable library itself, I had hoped it was in networkmanager-qt.

**EDIT:** ah this diff is on OpenConnect. Well, same thing, KDE supports it, https://invent.kde.org/plasma/plasma-nm/-/blob/master/vpn/openconnect/openconnectwidget.cpp?ref_type=heads#L189. We can probably reuse logic.

2026-04-15 08:36 UTC, pvuorela commented on src/nemo-connectivity/settingsvpnmodel.cpp
> +                if (element.tagName() == "Name") {
There are two formats handled here. The linked classes are using some settings classes but suppose there could be xml parsing somewhere deeper. However it shouldn't be really that special, both the formats just require finding a specific container element and reading a few things from there.

2026-05-11 19:19 UTC, PureTryOut commented on src/nemo-connectivity/settingsvpnmodel.cpp
> +                if (element.tagName() == "Name") {
I made #18 to replace this PR with and redid the config file parsing logic.

2026-05-14 11:00 UTC, pvuorela commented
Better working version merged.

2026-05-14 11:00 UTC, closed without merging